# Not sure if we can plop this in and build it with clang, so for now, just
# compile with binaries built by gcc... 
ifeq ($(TOOLCHAIN),gcc)
DEPS += liblsm
CFLAGS += -I$(LIB_ROOT)/liblsm/src/include
else # TOOLCHAIN != gcc

# liblsm is special because it has to be compiled by GCC, not Clang,
# even if the app is built with Clang
CFLAGS += -I$(LIB_ROOT)/liblsm/src/include
LFLAGS += -L$(LIB_ROOT)/liblsm/bld/gcc
LIBS += -llsm

endif # TOOLCHAIN != gcc
